backend:
  name: github
  repo: marcosabb/q
  branch: master
  site_domain: https://quizi.netlify.com/

publish_mode: editorial_workflow
media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: 'document'
    label: 'Document'
    folder: 'data/documents'
    create: true
    slug: '{{slug}}'
    editor:
     preview: false
    fields:
      - { label: 'Type', name: 'type', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Game', name: 'game', widget: 'string' }
      - label: 'Image', 
        name: 'image', 
        widget: 'object'
        - { label: 'Name', name: 'name', widget: 'string'}
        - { label: 'Source', name: 'src', widget: 'string'}
      - { label: 'Featured', name: 'featured', widget: 'boolean' }

      # -
      # - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      # - { label: 'Description', name: 'description', widget: 'string' }
      # - { label: 'Body', name: 'body', widget: 'markdown' }