backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: 'document'
    label: 'Document'
    folder: 'data/documents'
    create: true
    slug: '{{slug}}'
    editor:
     preview: false
    fields:
      - { 
        label: 'Type', 
        name: 'type', 
        widget: 'select', 
        options: ['quiz', 'test']
      }

      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Game', name: 'game', widget: 'string' }

      - label: 'Image'
        name: 'image'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'name', widget: 'string'}
          - { label: 'Source', name: 'src', widget: 'string'}
          
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: false }

      - label: 'Questions'
        name: 'questions'
        widget: 'list'
        fields:
          - { label: 'Id', name: 'id', widget: 'string'}
          - { label: 'Title', name: 'title', widget: 'string'}
          - label: 'Options'
            name: 'options'
            widget: 'list'
            fields:
              - { label: 'Key', name: 'key', widget: 'string' }
              - { label: 'Text', name: 'text', widget: 'string' }
        
      - label: 'Result'
        name: 'result'
        widget: 'object'
        fields: 
          - label: 'Statement'
            name: 'statement'
            widget: 'object'
            fields:
              - { label: 'Final', name: 'final', widget: 'string' }
              - { label: 'Share', name: 'share', widget: 'string' }
          - label: 'Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Id', name: 'id', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Image'
                name: 'image'
                widget: 'object'
                fields:
                  - { label: 'Name', name: 'name', widget: 'string'}
                  - { label: 'Source', name: 'src', widget: 'string'}